name: Sample Blog
author: ZhouYang
markdown: redcarpet
pygments: true
baseurl: /
url:
description: Tech Record
github: http://www.github.com/halochou
twitter: http://www.twitter.com/
facebook: http://www.facebook.com
linkedin: http://www.linkedin.com
email: rnpatel[at]me.com
location: 42°2'16"N   70°12'47"W
disqus: diqus-username

##Make sure to edit the above fields, especially for disqus.

